import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Recreate __filename and __dirname in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');

function getGitBranch() {
  // 1. Try Vercel's git ref first (build environment)
  if (process.env.VERCEL_GIT_COMMIT_REF) {
    return process.env.VERCEL_GIT_COMMIT_REF.trim();
  }

  // 2. Try other common CI env variables
  if (process.env.GITHUB_REF_NAME) {
    return process.env.GITHUB_REF_NAME.trim();
  }
  if (process.env.CI_COMMIT_REF_NAME) {
    return process.env.CI_COMMIT_REF_NAME.trim();
  }

  // 3. Fallback to git command
  try {
    const branch = execSync('git rev-parse --abbrev-ref HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
    return branch;
  } catch (err) {
    console.warn('[setup-env] Could not determine git branch via git command, defaulting to "main".');
    return 'main';
  }
}

function main() {
  const branch = getGitBranch();
  console.log(`[setup-env] Detected git branch: "${branch}"`);

  let apiBaseUrl = 'https://api.dbscore.in';

  if (branch === 'dbs/demo') {
    apiBaseUrl = 'https://api-staging.dbscore.in';
  }

  console.log(`[setup-env] Target API base URL: ${apiBaseUrl}`);

  // We write VITE_DBS_API_BASE_URL (used by apiClient.ts) and VITE_API_BASE_URL (defined in specs)
  const envContent = `# Auto-generated by setup-env.js based on git branch "${branch}"
VITE_DBS_API_BASE_URL=${apiBaseUrl}
VITE_API_BASE_URL=${apiBaseUrl}
`;

  try {
    fs.writeFileSync(envPath, envContent, 'utf8');
    console.log(`[setup-env] Successfully wrote .env file to: ${envPath}`);
  } catch (err) {
    console.error(`[setup-env] Error writing .env file:`, err);
    process.exit(1);
  }
}

main();
